package com.luanxv.pre.wechatAI.core;

import com.luanxv.pre.wechatAI.config.BotConfig;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Optional;

/** Persists each user's latest image, whether it was uploaded or generated by the bot. */
@Component
public class GeneratedImageStore {
    private final Path rootDirectory;

    public GeneratedImageStore(BotConfig config) {
        this.rootDirectory = Path.of(config.getGeneratedImageDirectory()).toAbsolutePath().normalize();
    }

    public void save(String userId, byte[] imageBytes) throws IOException {
        if (imageBytes == null || imageBytes.length == 0) {
            throw new IllegalArgumentException("Image data must not be empty");
        }
        Path target = imagePath(userId);
        Files.createDirectories(target.getParent());
        Path temporary = target.resolveSibling(target.getFileName() + ".tmp");
        Files.write(temporary, imageBytes);
        try {
            Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (AtomicMoveNotSupportedException ignored) {
            Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    public Optional<StoredImage> load(String userId) throws IOException {
        Path target = imagePath(userId);
        if (Files.isRegularFile(target)) {
            byte[] bytes = Files.readAllBytes(target);
            return Optional.of(new StoredImage(bytes, detectMimeType(bytes)));
        }
        // Preserve compatibility with images cached by an earlier version of the bot.
        Path legacyTarget = target.resolveSibling("last-generated.png");
        if (Files.isRegularFile(legacyTarget)) {
            byte[] bytes = Files.readAllBytes(legacyTarget);
            return Optional.of(new StoredImage(bytes, detectMimeType(bytes)));
        }
        return Optional.empty();
    }

    public boolean hasEditableImage(String userId) {
        try {
            return load(userId).isPresent();
        } catch (IOException exception) {
            System.err.println("检查图片缓存失败: " + exception.getMessage());
            return false;
        }
    }

    private Path imagePath(String userId) {
        return rootDirectory.resolve(hashUserId(userId)).resolve("last-editable-image");
    }

    private String hashUserId(String userId) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(userId.getBytes(StandardCharsets.UTF_8));
            StringBuilder result = new StringBuilder();
            for (byte value : digest) {
                result.append(String.format("%02x", value));
            }
            return result.toString();
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is unavailable", exception);
        }
    }

    private static String detectMimeType(byte[] bytes) {
        if (bytes.length >= 8 && bytes[0] == (byte) 0x89 && bytes[1] == 'P' && bytes[2] == 'N' && bytes[3] == 'G') {
            return "image/png";
        }
        if (bytes.length >= 3 && bytes[0] == (byte) 0xFF && bytes[1] == (byte) 0xD8 && bytes[2] == (byte) 0xFF) {
            return "image/jpeg";
        }
        if (bytes.length >= 12 && bytes[0] == 'R' && bytes[1] == 'I' && bytes[2] == 'F' && bytes[3] == 'F'
                && bytes[8] == 'W' && bytes[9] == 'E' && bytes[10] == 'B' && bytes[11] == 'P') {
            return "image/webp";
        }
        if (bytes.length >= 2 && bytes[0] == 'B' && bytes[1] == 'M') {
            return "image/bmp";
        }
        return "image/png";
    }

    public record StoredImage(byte[] bytes, String mimeType) { }
}
