package com.clawbot.wechatbot.intent;

public enum IntentType {
    BILIBILI_SUBSCRIBE_URL,
    BILIBILI_SUBSCRIBE_INDEX,
    BILIBILI_SUBSCRIBE_TITLE,
    BILIBILI_SEARCH_TITLE,
    BILIBILI_MARK_TITLE,
    BILIBILI_RECOMMEND,
    IMAGE_GENERATION,
    DOCUMENT_GENERATION,
    TOOL_QUERY,
    MULTI_TASK,
    GENERAL_CHAT
}
